### PR TITLE
Add JKSM path

### PR DESCRIPTION
**Pull request by architdate**
duplicate pull request from another original author since the pull request seemed to be abandoned.

### CODE REVIEW

**Comment by kwsch** [comment]
I'll manually update the original pull request; I feel like changing how it's set up anyway ;)

**Comment by sora10pls** [comment]
Just as a heads up @kwsch, these two PRs shouldn't even be implemented anyway. I just tested JKSM with Rosalina Homebrew Menu, and it still exports/imports save data from `/JKSV/Saves`... I dunno where OP from the original PR found that path, but it's definitely not where saves are stored.

**Comment by architdate** [comment]
ohh shit!! sry abt that then :/

**Comment by sora10pls** [comment]
That's alright, Kurt will more than likely remove the path from the PR when he redoes how paths are loaded. :P

**Comment by kwsch** [comment]
already been done:
https://github.com/kwsch/PKHeX/commit/7efd771bf4eb3ddc630ae88c85ad9abcb88bb06a#diff-bb08bde67df33281bd6d147764ba7077R44

**Comment by sora10pls** [comment]
Didn't even see that commit!

**Pull request closed without merging**
