### PR TITLE
Revise several legality check strings

### PR DESCRIPTION
**Pull request by sora10pls**
pokemon/Pokemon -> Pokémon
egg -> Egg
generation -> Generation

### CODE REVIEW

**Comment by kwsch** [comment]
the strings in the source code end up getting overwritten by the language files :)

**Comment by sora10pls** [comment]
Totally forgot about those, will replicate changes in the English language file and commit again.

**Comment by kwsch** [comment]
these line endings tho lol

**Comment by sora10pls** [comment]
Not even sure how that happened. That seems to only pop up in the commit on GitHub, and the strings load properly when built. :P

**Pull request merged**
