### PR TITLE
adjust to game

### PR DESCRIPTION
**Pull request by pokecal**
I discovered the difference, but I don't know CHT well, so if these changes adversely affects readability, please reject.

### CODE REVIEW

**Comment by Mrtops** [comment]
Please provide a description of changes (tools used).

**Comment by pokecal** [comment]
Typo fix, CHT_alternative species name list. Confirmed using CHT Moon.
Doduo, Dodrio, Rhydon, Mr.Mime, Sneasel, Linoone, Torterra, Buneary, Finneon, Weavile, Unfezant, Whirlipede, Sigilyph, Tornadus, Carbink, Palossand, Pyukumuku, Tapu Bulu, Kartana.

**Comment by pokecal** [comment]
I'm worried, original alternative-characters come from, prepared from outside of game (PGL or somewhere), or intentionally replaced for readability.

**Comment by kwsch** [comment]
Tagging @easyworld @CaiMiao

**Comment by CaiMiao** [comment]
These changes is correct and supposed to be approved.

**Comment by CaiMiao** [comment]
Original is just like a spelling mistake and these changes corrects them.

**Pull request merged**
