### PR TITLE
Update flags_e_en.txt

### PR DESCRIPTION
**Pull request by mi-ya1987**

### CODE REVIEW

**Comment by mi-ya1987** [comment]
Of course, I understand that you don't check every file thoroughly.
I also know that you are not responsible for finding spelling errors in every file.
The gen3 files are old, so few people use them, and it's only natural that mistakes are left untouched.
However, I don't understand why you didn't correct "Elixier" to "Elixir" when you rejected "Thunder stone".
You realized this mistake at that time too.
I'd like to know why you didn't correct "Elixir" just because you dismissed "Thunder stone".

**Comment by Lusamine** [comment]
I think the problem is you do not understand the GitHub workflow.

I did not address "Elixir" because the correction was appropriate.  I addressed "Thunder stone" because the correction was not appropriate.

This is what's supposed to happen:
1. YOU open the pull request to fix "Thunderstone" and "Elixier".
2. I make a suggestion to fix "Thunderstone" only.  "Elixier"'s fix is already correct.
3. YOU correct the pull request based on the suggestion. You can either edit the original pull request, or close it and open a new one if you don't know how to do it.

When you opened 2 pull requests to fix the same thing, this caused a problem because I cannot merge both of them. You must either close the original pull request or make the edit to the original pull request.

It sounds like you are making this into an accusation that "You did not correct it, and you knew it was correct." I do not need to make a suggestion about a correction that was correct. I was waiting for you to fix the original pull request and did not realize you opened two pull requests to fix the same thing, because that is not the correct action.

**Comment by mi-ya1987** [comment]
As you say, this is my first time using GitHub, and it's not localized in Japanese, so I'm fumbling around.

Perhaps in the chart you showed, I think
en7
I don't know how to fix it after this.
I don't know where No.3 is.

Please understand that I don't mean to criticize you, but I didn't know that "Elixir" was correct as of No.2.
So I think the proposal was simply rejected.

"Fork" use means that I can make further corrections without conflicting with your checks, am I right?
Also, can I ask you to check multiple files at once use "Fork"?

**Comment by Lusamine** [comment]
A fork is a copy of the repo, but it belongs to you.

If you follow my video, it allows you to create a copy, edit your own copy, and then propose all the changes at the same time. This will include all of the files you changed at once.

To do No.3 in my list, this is what you would do:

Every time you edit a file on kwsch's repo, it makes a new branch on your fork. You cannot edit kwsch's repo, only your own repo.
image

In this example, this pull request came from the branch `patch-15` from your fork.

https://github.com/mi-ya1987/PKHeX/branches
If you click on your fork and click on the branches, you should be able to find `patch-15`.
image

image
If you click this and edit this, it will make further changes to the pull request you already have open.

image
As you can see, this changes the branch to `patch-15`, where I already pushed a fix to `patch-15`. When you update `patch-15`, the pull request for it is automatically updated.

If you need further help using GitHub, I would suggest opening a [Discussion](https://github.com/kwsch/PKHeX/discussions) instead. Pull requests are for discussing the current code suggestion and this pull request is already closed.

**Comment by mi-ya1987** [comment]
Can I actually practice once?
If you say o.k. , in "const_e_ja.txt", "Wild Pokemon" on line 12 is intentionally mistaken for "野生なポケモン", so please point it out.
I will correct it to "野生のポケモン".

**Comment by Lusamine** [comment]
You need to open a new pull request. You can't edit one that's already merged and closed.

**Comment by mi-ya1987** [comment]
Another question, if I find one glaring mistake in one file and fix it perfectly right, is there any need to "Fork" it?

**Comment by Lusamine** [comment]
Yes, you can only make changes to your fork, and pull requests are from your fork. If you do not have a fork, you cannot make edits or pull requests.

**Comment by mi-ya1987** [comment]
o.k.
May I actually practice once?

**Comment by Lusamine** [comment]
You can go to your fork, click "Sync fork" to make sure it is updated, make the change to the file, then make the pull request like I showed you.
image

Again, if you need more help, please open a [Discussion](https://github.com/kwsch/PKHeX/discussions) instead.

**Pull request merged**
