### PR TITLE
convert Crystal locations

### PR DESCRIPTION
**Pull request by pokecal**
I don't know what pkl byte means, I applied a function that convert
mapID to pkm.metlocationID.
This function is used when caught mons.
e.g. route29(18,03): (18-1)<<1=2E, rom[9402E]=4C79, 9*(03-1)=12,
4C79+5+12=4C90, rom[94C90]=02.

I have NOT confirmed these converted data is correct.

### CODE REVIEW

**Comment by kwsch** [comment]
it's just an arbitrary extension for "**PK**HeX **L**egality Binary", the files are packed via the game's 'mini' format, pretty much just concatenation with an offset table.

**Comment by javierhimura** [comment]
I think we still are missing the met location for fishing encounters pkl file.

**Comment by pokecal** [comment]
Fount that fishingEncountTableIdOffset is metLocationIdOffset+3,
I made convert array, but I don't know where to put this. Fishability is considered.
return -1: also not fishable.
return 0 to 12: this is fishing encounter table ID.
return greater than 0x0F: 2 encounterID includes. only 2 maps return this.
  OlivineCity(1B) return 0x10: HarborSide is encID1, CitySide is 0.
  SilverCave(2E) return 0x32: Outside is encID3, innerCave is 2.

convMapIDtoFishLocationID = new[0x80] {
    -1, 1,-1, 0, 3, 3, 3,-1,10, 3, 2,  -1,-1, 2,   3, 0,
    -1,-1, 3,-1,-1,-1, 3,-1,-1,-1,-1,0x10,-1,-1,   0, 9,
     1, 0, 2, 2,-1, 3, 7, 3,-1, 3, 4,   8, 2,-1,0x32, 1,
    -1, 3,-1,-1,-1,-1,-1, 0, 2, 2,-1,  -1, 3, 1,  -1,-1,
    -1, 2,-1, 2,-1,-1,-1,-1,-1,-1,12,  12, 0,-1,  -1,-1,
    -1, 7, 0, 1,-1, 1, 1, 3,-1,-1,-1,   1, 1, 2,   3,-1,
    -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,  -1,-1,-1,  -1,-1,
    -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,  -1,-1,-1,  -1,-1, };

**Comment by kwsch** [comment]
note to self:
Change getAreas2_F to return List\<EncounterArea> (not IEnumerable\<EncounterArea>)
Replace getArray2_F with following:
```
public static EncounterArea[] getArray2_F(byte[] data)
{
    int ofs = 0;
    var f = getAreas2_F(data, ref ofs);
    
    // Fishing Tables are not associated to a single map; a map picks a table to use.
    // For all maps that use a table, create a new EncounterArea with reference to the table's slots.
    var convMapIDtoFishLocationID = 
    {
        -1,  1, -1,  0,  3,  3,  3, -1, 10,  3,  2, -1, -1,  2,  3,  0, 
        -1, -1,  3, -1, -1, -1,  3, -1, -1, -1, -1, 16, -1, -1,  0,  9, 
         1,  0,  2,  2, -1,  3,  7,  3, -1,  3,  4,  8,  2, -1, 50,  1, 
        -1,  3, -1, -1, -1, -1, -1,  0,  2,  2, -1, -1,  3,  1, -1, -1, 
        -1,  2, -1,  2, -1, -1, -1, -1, -1, -1, 12, 12,  0, -1, -1, -1, 
        -1,  7,  0,  1, -1,  1,  1,  3, -1, -1, -1,  1,  1,  2,  3, -1, 
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    };
    var areas = new List<EncounterArea>();
    for (int i = 0; i < convMapIDtoFishLocationID.Length; i++)
    {
        var loc = convMapIDtoFishLocationID[i];
        if (loc == -1) // no table for map
            continue;
            
        areas.Add(new EncounterArea { Location = i, Slots = f[loc].Slots });
    }
    return areas.ToArray();
}
```

I'm not able to try it out atm, will check later.

**Comment by kwsch** [comment]
note to self:
Change getAreas2_F to return List
Replace following method:
```
public static EncounterArea[] getArray2_F(byte[] data)
{
    int ofs = 0;
    var f = getAreas2_F(data, ref ofs);
    
    // Fishing Tables are not associated to a single map; a map picks a table to use.
    // For all maps that use a table, create a new EncounterArea with reference to the table's slots.
    var convMapIDtoFishLocationID = 
    {
        -1,  1, -1,  0,  3,  3,  3, -1, 10,  3,  2, -1, -1,  2,  3,  0, 
        -1, -1,  3, -1, -1, -1,  3, -1, -1, -1, -1,  0, -1, -1,  0,  9, 
         1,  0,  2,  2, -1,  3,  7,  3, -1,  3,  4,  8,  2, -1,  2,  1, 
        -1,  3, -1, -1, -1, -1, -1,  0,  2,  2, -1, -1,  3,  1, -1, -1, 
        -1,  2, -1,  2, -1, -1, -1, -1, -1, -1, 12, 12,  0, -1, -1, -1, 
        -1,  7,  0,  1, -1,  1,  1,  3, -1, -1, -1,  1,  1,  2,  3, -1, 
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    };
    var areas = new List<EncounterArea>();
    for (int i = 0; i < convMapIDtoFishLocationID.Length; i++)
    {
        var loc = convMapIDtoFishLocationID[i];
        if (convMapIDtoFishLocationID[i] == -1) // no table for map
            continue;
        areas.Add(new EncounterArea { Location = i, Slots = f[loc].Slots });
    }
    
    // Some maps have two tables. Fortunately, there's only two. Add the second table.
    areas.Add(new EncounterArea { Location = 0x1B, Slots = f[1].Slots }); // Olivine City (Tables 0 = Harbor & 1 = City)
    areas.Add(new EncounterArea { Location = 0x2E, Slots = f[3].Slots }); // Silver Cave (tables 2 = Inside & 3 = Outside)
    return areas.ToArray();
}
```

Can't test atm, will later.
Hardcoded the split tables separately as it's a little cleaner.

**Pull request merged**
