### PR TITLE
add UltraRide SlidePad flag

### PR DESCRIPTION
**Pull request by pokecal**
SlidePad will be enabled from the first play.

### CODE REVIEW

**Comment by sora10pls** [comment]
Slight nitpick: official name is Circle Pad, line should read:

`Circle Pad Controls for Ultra Warp Ride` :)

**Comment by pokecal** [comment]
oops
It's already merged, push -f or re-request is fine? or I will fix it when add other flags.

**Comment by kwsch** [comment]
Later is fine; I plan to have a stable release in the next 14h for the game release :)

**Comment by pokecal** [comment]
OK, I will spit up after your big work. there are few turns, but I'm now stockpiling.

**Comment by kwsch** [comment]
I mean, you can submit it any time before then.
Things are pretty much settled but small text changes are fine.

**Pull request merged**
