### PR TITLE
Create flags_b2w2_es.txt

### PR DESCRIPTION
**Pull request by XxPhoenix1996xX**

### CODE REVIEW

**Comment by ReignOfComputer** [comment]
Perhaps, this should all be in ONE single pull request?

**Comment by XxPhoenix1996xX** [comment]
Probably yes. I don't know how to do this in a sigle pull request tho. I don't really use Github.

**Comment by architdate** [comment]
Just need to do it all in the same branch instead of having separate branches for each

**Comment by XxPhoenix1996xX** [comment]
Ok, sorry guys!

**Pull request closed without merging**
