### PR TITLE
Rivise Chinese official translations

### PR DESCRIPTION
**Pull request by CaiMiao**

### CODE REVIEW

**Comment by kwsch** [comment]
Since I cannot speak Chinese, I'll wait until more people weigh in on these changes.

**Comment by CaiMiao** [comment]
I have got in touch with original translator @easyworld and he also agrees these changes.

**Comment by CaiMiao** [comment]
text_EncounterType_xx.txt is not properly loaded as an unicode text.

**Comment by easyworld** [comment]
@CaiMiao did a lot about the texts. His work is good, I think.

**Pull request merged**
