### PR TITLE
Optimize all png images in PKHeX.Drawing

### PR DESCRIPTION
**Pull request by ndye**

### CODE REVIEW

**Comment by kwsch** [comment]
Related: https://github.com/kwsch/PKHeX/pull/517

**Comment by kwsch** [comment]
Can you provide any details on what tools/settings were used to optimize the png compression?

I don't see any issue with the sprites on my windows machine, but due to prior attempts by others being unsuccessful for running under mono/wine, I don't feel it is appropriate to merge until someone can confirm this commit doesn't result in the same error as seen in #557.

**Comment by ndye** [comment]
Sure, so I actually run on macOS so I can confirm that it runs on mono/wine and as for the settings a actually used opting and if you have ever used it it essentially attempts all of the possible compression options for the file and chooses the best one. if you are interested the actual command used to compress them is:
`optipng -o7 -zm1-9 -strip all -clobber -fix *.png`

**Comment by kwsch** [comment]
Cool; can you confirm that hovering over the slots produces the intended glow effect, and that the sprites retain their original transparency appearance (see the readme for the expected view, and compare it to the referenced issue where the sprite turned black)

**Pull request merged**
