### PR TITLE
Update lang_zh.txt

### PR DESCRIPTION
**Pull request by kckxpyr1**

### CODE REVIEW

**Comment by Lusamine** [comment]
The English button only says "Raids", which I believe should be 团战?
image
It looks like your translation adds "Editor" to the end.

**Comment by FireJoker** [comment]
I think "团体战" could be better.

**Comment by Kitcham** [comment]
I think "團體戰" is better for CHT translation, and "团体战" is better for CHS translation.

Both translation texts are taken from the [official Pokémon website in Hong Kong](https://sv-news.pokemon.co.jp/tc/page/21.html). "太晶" means "Tera" in English, "團體戰" and "团体战" mean "Raid".

If possible, can you please update the traditional Chinese version as well? @kckxpyr1  Thanks!

CHT
CHS

**Comment by Lusamine** [comment]
This was handled in https://github.com/kwsch/PKHeX/pull/3717 so I'm closing this. Thanks to everyone for the input!

**Pull request closed without merging**
