### PR TITLE
Update some file for the FR language

### PR DESCRIPTION
**Pull request by bettydreemurr**

### CODE REVIEW

**Comment by kwsch** [comment]
Remember to update the main readme to add the link to fr, similar to the previous es

**Comment by yanisdreemurr** [comment]
Ah yes indeed, I will also do it on NHSE at the same time

**Comment by bettydreemurr** [comment]
the items translated into Korean are taken from the site: https://bulbapedia.bulbagarden.net

**Comment by kwsch** [comment]
The text_*_lang files are raw files dumped from the game; those are the met locations that show for the languages in-game. Pokémon GO isn't localized :)

**Comment by bettydreemurr** [comment]
Oh I see, haha x)

**Pull request merged**
