### PR TITLE
Fix more HGSS met location typos

### PR DESCRIPTION
**Pull request by sora10pls**
Overlooked these two when previously committing.

`263` => `163` (Route 15)
`100` => `200` (Rock Tunnel)

### CODE REVIEW

**Comment by kwsch** [comment]
Please update your PR (add in the last one) to be based off the latest refactoring commit :P

**Comment by sora10pls** [comment]
I get the following from Visual Studio when trying to do so:

C:\Users\Matt\Source\Repos\PKHeX\PKHeX.Core\PKHeX.Core.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\Matt\Source\Repos\PKHeX\PKHeX.Core\PKHeX.Core.csproj

I'd like to try and sort this out quickly but I've got work in the morning :(

**Comment by sora10pls** [comment]
Perhaps if you're able to, commit the changes yourself and I'll get this all sorted on my end tomorrow after work.

**Comment by kwsch** [comment]
Gotta update to vs2015 v3 with core tools, or latest vs2017

http://stackoverflow.com/questions/42509313/the-default-xml-namespace-of-the-project-must-be-the-msbuild-xml-namespace

**Pull request closed without merging**
