### PR TITLE
Add WCS 2024 Steenee date

### PR DESCRIPTION
**Pull request by 9Bitdo**
- Add WCS 2024 [Steenee] date

https://x.com/SerebiiNet/status/1823882745493291076

Serebil's tweet on Steenee's distribution was on 15th Aug 00:41 UTC so there is possibility those on the UTC -1 to UTC -11 timezone could redeemed it on the 14th Aug 2024.

The distribution's end date stated on the redeem card provided by @Lusamine was stated Aug 30th 23:59 UTC. It would be possible for UTC +1 to +11 timezone to redeem it on the 31th Aug 2024.

i made the necessary changes to the date and also .pkl had been replaced.

thank you for the help provided by Lusamine and Manu

### CODE REVIEW

**Comment by Lusamine** [comment]
The gift was not redeemable at the time of Serebii's post, so it should not be used as a reference for the start date. I last tried approximately 9:23 PM Central Time on the 14th (which would be 2:23 AM UTC). If you know of any evidence that the WC was available and the gift was redeemable on August 14th, then use that date. Otherwise the 15th is known to work.

**Comment by 9Bitdo** [comment]
Thanks Lusamine, i want the distribution dates to be accurate and in line with PKHeX's belief. That will bring less issues and errors when using the mystery gift database in PKHeX. I will re-edit the date to 15th Aug and should there be any changes to the distribution date again i would update

**Comment by Lusamine** [comment]
It should be possible to add a commit to your master branch to fix the error, which will update this PR... there's no need to keep opening new PRs every time.

**Comment by 9Bitdo** [comment]
mb i didnt want to clutter the branch with alot of changes hence i make a new PR to make it neat and tidy. OCD

**Pull request closed without merging**
