### PR TITLE
Add Alex Dragapult Date

### PR DESCRIPTION
**Pull request by xiaolong11123**

### CODE REVIEW

**Comment by sora10pls** [comment]
November 16 is not an eligible date as of the time the serial code was revealed.

**Comment by xiaolong11123** [comment]
Have you calculated the time difference? I'm not sure, so I just subtracted
it by one day.

Matt ***@***.***>于2023年11月17日 周五21:07写道：

**Comment by sora10pls** [comment]
Yes, otherwise I would not have made the comment.

**Comment by xiaolong11123** [comment]
OK, I have changed it.

**Comment by Lusamine** [comment]
For future reference, the math is not to "subtract one from the date." The correct way to know the earliest date is to look for the earliest date anywhere on Earth at the time the serial code is revealed.

**Pull request merged**
