### PR TITLE
Localizing into Japanese

### PR DESCRIPTION
**Pull request by mi-ya1987**
In "const_e_ja.txt", "Wild Pokemon" on line 12 is intentionally mistaken for "野生なポケモン", so please point it out.
I will correct it to "野生のポケモン".

### CODE REVIEW

**Comment by Lusamine** [comment]
You can correct it whenever you want. You don't need someone to suggest that you change it. I don't understand Japanese so please fix it to the correct translation and let me know when you are done.

**Comment by mi-ya1987** [comment]
[Merge branch 'kwsch:master' into master](https://github.com/kwsch/PKHeX/pull/3792/commits/4374d4c30df7a6bee0725718df83ec09868a312c)

I didn't mean to choose this.

**Comment by kwsch** [comment]
> [Merge branch 'kwsch:master' into master](https://github.com/kwsch/PKHeX/pull/3792/commits/4374d4c30df7a6bee0725718df83ec09868a312c)
> 
> I didn't mean to choose this.

It's fine; all commits will be squashed into a single one summarizing all the changes made, by whoever merges it when you're done.

**Comment by Lusamine** [comment]
The merge is fine. It is because there were updates to kwsch's repository and your repository needed those updates.

Is the translation correct now?

**Comment by mi-ya1987** [comment]
Yes.
"な" to "の" is correct.

**Comment by mi-ya1987** [comment]
[Merge branch 'kwsch:master' into master](https://github.com/kwsch/PKHeX/pull/3792/commits/4374d4c30df7a6bee0725718df83ec09868a312c)

Are you okay with being displayed to me?
Are they all the same? No problem?

**Comment by Lusamine** [comment]
image
You can click on this to see what is changed.

https://github.com/kwsch/PKHeX/commits/master
You can click on the list of commits to see that once it is merged, it is clean.

**Comment by mi-ya1987** [comment]
Okay , I understood.
Thanks a lot!

**Pull request merged**
